version: '3'

networks:
  backend:
    driver: "bridge"

volumes:
  mongo:
    driver: "local"
  elasticsearch-data:
    driver: "local"
  elasticsearch-plugins:
    driver: "local"
  mysql:
    driver: "local"

services:
  ### MongoDB
  mongo:
    build: 
      context: ./mongo
    ports:
      - "27017:27017"
    volumes:
      - ./.data/mongo:/data/db
    networks:
      - backend

  ### Elasticsearch
  elasticsearch:
    build: ./elasticsearch
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - elasticsearch-plugins:/usr/share/elasticsearch/plugins
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - backend

  ### MySQL
  mysql:
    build:
      context: ./mysql
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_USER=default
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

  ### Redis
  redis:
    build: ./redis
    volumes:
      - ./.data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - backend

  ### Rabbitmq
  rabbitmq:
    build: ./rabbitmq
    environment:
      - RABBITMQ_LOGS=/var/log/rabbitmq/rabbit.log
      - RABBITMQ_NODENAME=rabbit
    volumes:
      - ./rabbitmq/rabbitmq.config:/tmp/rabbitmq.config:ro
      - ./.data/rabbitmq:/var/lib/rabbitmq:rw
      - ./.data/rabbitmq/logs:/var/log/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
